### ISSUE TITLE
[QUESTION] path transformation when creating tar file

### ISSUE THREAD

**Issue by fholzer** [isaacs/node-tar#271]
# What / Why
While I found an of old issue (#10) and a closed PR (#17) about transforming the file path when writing a tar file, and there are references to "this now being possible in v3" I couldn't find any documentation of example of how this can actually be done.
As there is no transform cb when creating a tar file that could be used to do that, and the low level API seems quite closed in terms of what is exposed to outside classes due to the extensive use of Symbols, I'm wondering if you could clarify if path transformations are sill possible with v6, and maybe some pointers in the right direction or how an implementation of this could look like.

**Comment by isaacs** [comment]
When _unpacking_ you can do this with an `onentry` method that changes the paths or a `transform` method that returns a new stream for the contents.  But when packing there's no straightforward way to change the paths as of tar v4.

I am open to adding both to the Pack class to match this feature of gnutar.

**Comment by isaacs** [comment]
Adding an `onentry` (which could modify path and other header information) is straightforward.  However, a _content_ transform is a bit more complicated, since the file reading and buffer-padding logic is all optimized and unrolled, rather than going through a Stream class.

**Comment by fholzer** [comment]
Closing this, as my issue was just about path transformation, not content transformation.

Thanks for this!

**Comment by gramakri** [comment]
Was path transformation when creating tar files implemented? The `onWriteEntry` is called too late for path transformation

**Comment by isaacs** [comment]
Indeed, it's being called after the Header is already encoded, so that's not much help, is it? Fixing now.
