### ISSUE TITLE
[BUG] Tar is very slow on npm 6.14.15

### ISSUE THREAD

**Issue by Tallyb** [isaacs/node-tar#293]
# What / Why

npm 6.14.15 is horribly slow, and it seems to result from upgrading `tar` from 4.4.14 to 4.4.19.

To reproduce you can try and install a package that needs to extract data like geo-tz(6.0.1). On GHA we saw an increase in npm install from 1 minute to 7 minutes!!!

Check out this repo github actions timing: 
https://github.com/Tallyb/slow-npm/actions/runs/1228854056

**Comment by theseion** [comment]
I can confirm that. However, its not the node version but NPM, 6.14.14 was fine 1.14.15 is not. The change of the `tar` version is from 4.4.15 to 4.4.19.

**Comment by theseion** [comment]
I've narrowed it down to 4.4.16. Tested with `material-design-icons` `3.0.1`.
NPM version: `6.14.14`

I manually changed the `tar` dependency in the npm package.json to `4.4.16`, then `npm i` (for npm). With that the processing time goes up from ~120 seconds to 300+ seconds.

**Comment by theseion** [comment]
Oh, just for future reference: I got here because my builds stopped working after the `node:lts-buster` image was upgraded last to use NPM 6.14.15. NPM would start timing out with "cb() never called".

**Comment by maxtrem271991** [comment]
> # Quoi / Pourquoi
> Le nœud 6.14.15 est horriblement lent, et il semble résulter de la mise `tar`à niveau de 4.4.14 à 4.4.19.
> 
> Pour reproduire, vous pouvez essayer d'installer un package qui doit extraire des données telles que geo-tz(6.0.1). Sur GHA, nous avons vu une augmentation de l'installation de npm de 1 minute à 7 minutes !!!
> 
> Consultez le calendrier des actions de ce dépôt github : https://github.com/Tallyb/slow-npm/actions/runs/1228854056

**Comment by kuzmeo** [comment]
I have similar performance issues on 7.x and 8.x npm versions as well. npm install runs 2-3 times slowly than on 6.14.13 npm version, though I didn't try 6.14.14

**Comment by psxpa3** [comment]
Hi @Tallyb I am trying to upgrade tar version from 4.4.8 to 6.1.9/6.1.10, however getting the following error - TypeError: Cannot destructure property isAbsolute of 'undefined' or 'null'.

   5 | import * as tmp from "tmp";
   6 | // import * as tar from "tar";
>  7 | const tar = require("tar");

Could you provide any direction on this?. It seems to be breaking at `tar.extract()`, but everything seems intact to me.

**Comment by theseion** [comment]
For reference, this appears to be the issue where people noticed that something was going on with NPM: https://github.com/npm/cli/issues/3676
