### ISSUE TITLE
[BUG] Tar upgrade from 6.1.0 to 6.1.9/6.1.10 throws error

### ISSUE THREAD

**Issue by psxpa3** [isaacs/node-tar#306]
Hello,
I am trying to upgrade tar version. However, getting this error 
 TypeError: Cannot destructure property `isAbsolute` of 'undefined' or 'null'.

       5 | import * as tmp from "tmp";
       6 | // import * as tar from "tar";
    >  7 | const tar = require("tar");

Could anybody provide some direction?

**Comment by isaacs** [comment]
What is the context in which you are loading tar?  Is this a node program?

`isAbsolute` is destructured from `require('path')`, which should definitely not be undefined or null.

**Comment by psxpa3** [comment]
Thanks for the reply @isaacs. Yes, it is a node program. The thing is I am trying to upgrade tar version from 6.1.0 to 6.1.1+, and `yarn test` fails with the above error

**Comment by isaacs** [comment]
Can you add a line in there like `console.log(require("path"))` to show what it's returning?

**Comment by janhavi529** [comment]
Hi @psxpa3 were you able to resolve this issue? I am trying to update tar to the same version and facing the same issue.

**Comment by isaacs** [comment]
Will reopen when the questions above are answered.

**Comment by jiaxin-ge** [comment]
@isaacs I am seeing similar issues as well. Here are some related information:
Error trace:
<img width="826" alt="Screen Shot 2023-06-08 at 9 27 08 PM" src="https://github.com/isaacs/node-tar/assets/86251867/4f424a1b-7769-4f89-b5a6-97c2fc41741a">
Dependencies:
<img width="375" alt="Screen Shot 2023-06-08 at 9 27 36 PM" src="https://github.com/isaacs/node-tar/assets/86251867/fe3d9688-3e23-4d2f-86dd-d3f07c806ef2">
My file: 
<img width="645" alt="Screen Shot 2023-06-08 at 9 28 08 PM" src="https://github.com/isaacs/node-tar/assets/86251867/ff406dca-c3ba-420e-ab84-96f8e1ff49ef">

Node version:  node: '16.18.0'

It would be really helpful if you could point me to the right direction! Thank you so much!
