### ISSUE TITLE
[FEATURE] customizable file header in `tar.c`

### ISSUE THREAD

**Issue by davidkhala** [isaacs/node-tar#316]
# What / Why
There is not equivalent like 'onentry' listener of tar.x in tar.c option
So develper might not be able to have a fine-grain control on how each file entry will be added to archive, especially for file header

An golang example here is to list out what parameters we want to manipulate
https://go.dev/src/archive/tar/common.go

## When
n/a

## Where
`tar.c(...`
### Current Behavior
we can have a archive level control flag in options like `portable`, `nomtime`, `mode`

### Expected Behavior
add a new options like
```
onentry: (entry)=>{}
```

## Who
n/a

## Drawback
let developer to make good use of low-level API like 
```
class tar.Header
...
```

**Comment by isaacs** [comment]
Spelled it `onWriteEntry`, since `onentry` is already taken. Renamed `onentry` to `onReadEntry` (with deprecated `onentry` alias) for clarity.
