### ISSUE TITLE
[FEATURE] Custom filenames in archive

### ISSUE THREAD

**Issue by psi-4ward** [isaacs/node-tar#317]
# What / Why

I've lot's of `<some-tmp-filename>` files which maps to a human-readable filename in a database so I want to rename the file inside the archive. 

Something like 
```js
tar.create( gzip: true }, [
  new PackJob('my_dog.jpg', path.resolve('ada9dj0j091j2e')),
  new PackJob('water-picture.jpg', path.resolve('pl9sn47fhbf')),
])
```

Or is this already possible? Looks like the API is too restrieced.

**Comment by psi-4ward** [comment]
used tar-stream for now: https://github.com/mafintosh/tar-stream/issues/24#issuecomment-1121211775

**Comment by isaacs** [comment]
You can do this as of 7.3 by modifying the entry in an `options.onWriteEntry` method.

**Comment by exotexot** [comment]
There is no documentation on how to use the options.onWriteEntry method...

**Comment by isaacs** [comment]
Oh, that's a good point. Added some docs on 02f883aa4d3336c023fb826d4ba11dde01c7f338.
