### ISSUE TITLE
[FEATURE]: expose support for brotli compression

### ISSUE THREAD

**Issue by JamieMagee** [isaacs/node-tar#390]
[`minizlib`][1] has had support for brotli compression since 1.3.0, which was updated here in https://github.com/isaacs/node-tar/commit/0973296be84a03312aca2bf74ae31a6b41469b29.

`tar(1)` has support for brotli compression currently via the `-I`/`--use-compress-program` option. For example:

```
tar -I brotli -cf archive.tar.br archive
```

But I've also proposed adding a top-level `--brotli` flag: https://lists.gnu.org/archive/html/bug-tar/2023-06/msg00002.html

[1]: https://www.npmjs.com/package/minizlib

**Comment by isaacs** [comment]
I like the idea.

In keeping with the pattern of mapping tar(1) options to node-tar options, I guess it'd be `{ I: 'brotli' }` or `{ useCompressProgram: 'brotli' }`?  It's a bit weird to call it a "compress program" when it's all the same "program" though 🫤 Maybe those two could be aliases for `compressAlgorithm` or something?

**Comment by JamieMagee** [comment]
`tar(1)` supports some algorithms (`bzip2`/`xz`/`lzip`/`lzma`/`lzop`/`zstd`) via `-I`/`--use-compress-program` that don't overlap with `node-tar`'s support.

I think adding a `brotli` option or a `compress` option would be simpler. So you can provide options like:

```js
const opts = {
  brotli: <true|brotli options> // same as gzip options
}
```

or

```js
const opts = {
  compress: {
    algorithm: 'brotli', // or 'gzip'
    options: {
      level: 9
    }
  }
}
```

What do you think?
