### ISSUE TITLE
tar seems to corrupt mac app bundle signature integrity

### ISSUE THREAD

**Issue by etodanik** [isaacs/node-tar#405]
I have a `tar` with a macOS *.app bundle inside. Let's say the name is `injector.app`.

If I use `tar -xf injector.app` to unpack it, and run a `codesign` verification command, I get:
```
codesign -v -vvv --deep --strict injector.app
dist/injector.app: valid on disk
dist/injector.app: satisfies its Designated Requirement
```

Same exact `tar` file extracted like so:
```javascript
await tar.x({
    file: tarFilePath,
    C: extractPath 
});
```

Results in:
```zsh
codesign -v -vvv --deep --strict dist/injector.app
dist/injector.app: code object is not signed at all
In subcomponent: /Users/danny/WebstormProjects/elixir-launcher/node_modules/@elixir/overlay/dist/injector.app/Contents/Frameworks/overlay.vert.spv
```

I consistently get the same results (consistent success via `tar` cli, or via "The Unarchiver", and consistent failure with `node-tar`)

EDIT: 
Some more random observations about the inner files that "lose" their signature:
- They have an identical SHA checksum hash
- Their attributes seem identical
- The only difference is running 'codesign' on them

**Comment by isaacs** [comment]
Well, as we learned back in tautology club, if something is different, then something is different.

Can you share the file? I'd be happy to take a look, maybe there's some attributes or something in the entry that tar(1) is respecting and node-tar isn't setting properly. It might not be possible to do the right thing from node, if it's some weird setopts call or something, but it might also be like a hidden file or hardlink or something that needs to be preserved.

**Comment by etodanik** [comment]
Yes, more than happy to share the file.
https://www.dropbox.com/scl/fi/cpwnt1vkzxaoa4nioe43j/injector-darwin-arm64.tar?rlkey=k6mvq6zjnlsczy3dixxljzj9h&dl=0

The steps are basically:
- Extract it
- Run `codesign -v -vvv --deep --strict injector.app` 
- `tar` should show a perfectly signed file, while `node-tar` should see a broken one

The file itself is part of a game launcher overlay.

**Comment by etodanik** [comment]
I'm curious what you'll find, if at all. But I'm seeing that mac's app bundles are brittle as hell. Essentially breathe on them wrong, they break. To the point where I had to opt out not just out of `node-tar` so far, but even basic things like `fs-extra` commands like `copySync`. 

tar(1) and cp(1) all work wonderfully and respect Apple's various nuances of how the security works with the bundles and the filesystem, but anything I tried from within node so far wreaks total havoc.

**Comment by isaacs** [comment]
Yeah, I think this is depending on some stuff that Darwin adds above the bare POSIX fs layer. A binary tar implementation can call whatever os-specific stuff it wants, but a library running on Node can only do what node provides interfaces for. So node-tar can't set arbitrary ACLs and other stuff, because there's just no way to do it.

The only difference that jumps out at me, looking at what node-tar and bsdtar unpack, is there are a few files like `injector.app/Contents/Frameworks/._overlay.vert.spv`, which don't appear in the bsdtar unpack. Maybe those are supposed to be some Apple magic that gets incorporated into the corresponding file somehow? The contents of these files seems to be very Apple ACL-related.

```
$ strings gh-405/injector.app/Contents/Frameworks/._overlay.metallib
Mac OS X        
ATTR
com.apple.cs.CodeDirectory
com.apple.cs.CodeRequirements
 com.apple.cs.CodeRequirements-1
com.apple.cs.CodeSignature
<overlay
N68X37B8H8
overlay
subject.OU
N68X37B8H8
<overlay
N68X37B8H8
%T_9
Apple Inc.1&0$
Apple Certification Authority1
Apple Root CA0
120201221215Z
270201221215Z0y1-0+

$Developer ID Certification Authority1&0$
Apple Certification Authority1
Apple Inc.1
)xEii`k_
1? v(m
'0%0#
http://crl.apple.com/root.crl0
B9tk
P9jDt
#q-_

xXI
   (
 "ror
Apple Inc.1&0$
Apple Certification Authority1
Apple Root CA0
060425214036Z
350209214036Z0b1
Apple Inc.1&0$
Apple Certification Authority1
Apple Root CA0
, op
https://www.apple.com/appleca/0
Reliance on this certificate by any party assumes acceptance of the then applicable standard terms and conditions of use, certificate policy and certification practice statements.0
=&g 
Sj[d
uu!0
0y1-0+

$Developer ID Certification Authority1&0$
Apple Certification Authority1
Apple Inc.1
211014201130Z
261015201129Z0
N68X37B8H81B0@

9Developer ID Application: Satoshis Games, SL (N68X37B8H8)1
N68X37B8H81
Satoshis Games, SL1
p$Y?
Q"J'w
3+\yn
f+DYB
40200
$http://ocsp.apple.com/ocsp03-devid060
Reliance on this certificate by any party assumes acceptance of the then applicable standard terms and conditions of use, certificate policy and certification practice statements.06
*http://www.apple.com/certificateauthority/0
20211014000000Z0
P~8g*
Q$(w
5$|0hL
0y1-0+

$Developer ID Certification Authority1&0$
Apple Certification Authority1
Apple Inc.1
240402190913Z0/
9q8(
t50-
FXd`
H<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>cdhashes</key>
<array>
<data>
8zlxOCgYUO4EH9po9h4WzYyhdDU=
</data>
<data>
CMB1pbVdqvMS+rdtuxNHfmbWRlg=
</data>
</array>
</dict>
</plist>
\U+S
b\g^
20240402190913Z0
0|100.

'Apple Timestamp Certification Authority1&0$
Apple Certification Authority1
Apple Inc.1
240318202045Z
240429202044Z0B1
Timestamp Signer RNO11
Apple Inc.1
\X':
http://www.apple.com/appleca0
Reliance on this certificate by any party assumes acceptance of the then applicable standard terms and conditions of use, certificate policy and certification practice statements.0
,0*0(
"http://crl.apple.com/timestamp.crl0
|__k1
7>Sk,
60 ^g
 i?f
}LWc
Apple Inc.1&0$
Apple Certification Authority1
Apple Root CA0
120405120244Z
270405120244Z0|100.

'Apple Timestamp Certification Authority1&0$
Apple Certification Authority1
Apple Inc.1
Im] 
(ny_~
&By^
t-D>
E~4u&
'0%0#
http://crl.apple.com/root.crl0
mzT_
Bsu|QC
:m7(
FeoU
Apple Inc.1&0$
Apple Certification Authority1
Apple Root CA0
060425214036Z
350209214036Z0b1
Apple Inc.1&0$
Apple Certification Authority1
Apple Root CA0
, op
https://www.apple.com/appleca/0
Reliance on this certificate by any party assumes acceptance of the then applicable standard terms and conditions of use, certificate policy and certification practice statements.0
=&g 
Sj[d
uu!1
0|100.

'Apple Timestamp Certification Authority1&0$
Apple Certification Authority1
Apple Inc.1
240402190913Z0#
K@37
740+
:O3G
ry*3q
Xgw6
```

I really don't think there's anything that can be done, short of a binary add-on to set the os-specific stuff when it sees one of those `._` files. Node-tar is unpacking them just as they are listed in the tarball.
