### ISSUE TITLE
v7 breaks sinon stubbing

### ISSUE THREAD

**Issue by hldswrth** [isaacs/node-tar#410]
We use sinon in our (common JS) unit tests for code which uses the tar.x function.  This work fine with v6.
```
const tar = require('tar')
const sinon = require('sinon')
const tarXStub = sinon.stub(tar, 'x')
.. run test for code which calls the x function...
tarXstub.restore()
```

When using v7 with no other changes to our code or tests, the tests which involve the x function fail with error `TAR_BAD_ARCHIVE: Unrecognized archive format` which indicates the stubbing is not effective, despite the sinon.stub and sinon.restore calls appearing to be successful.

**Comment by hldswrth** [comment]
Thanks for the quick response. I did try changing my code to call tar.extract insted of tar.x but this cannot be stubbed by sinon, doing a `sinon.stub(tar, 'extract')` results in `TypeError: Descriptor for property extract is non-configurable and non-writable`.
If I `require('tar/extract')` I don't see how I would stub that with sinon.

**Comment by AviVahl** [comment]
Rather than requiring `tar` in the _implementation_, require `tar/extract` and use the `extract` fn exported from that module.

Do the same where you mock. That module directly exports the fn `extract`, meaning it can be mocked, as it's not a getter.

**Comment by hldswrth** [comment]
Thanks!  The following does appear to at least pass unit tests again:
```
// code:
const extract = require('tar/extract')
return extract.extract(options)

// test:
const extract = require('tar/extract')
const extractStub = sinon.stub(extract, 'extract')
```
