### ISSUE TITLE
unpack strip error

### ISSUE THREAD

**Issue by rzyanhao** [isaacs/node-tar#411]
this error is caused by this commit :  https://github.com/isaacs/node-tar/commit/fe8cd57da5686f8695415414bda49206a545f7f7
![image](https://github.com/isaacs/node-tar/assets/9431954/fcf7b6f4-cb84-4421-9353-e3cb56274a28)
as the red lines in this picture, the "p" passed into to `stripAbsolutePath(p)` is not right, because it may be modified when it has strip

**Comment by isaacs** [comment]
What is the error that you are referring to? How can I reproduce it?

**Comment by rzyanhao** [comment]
for example,  the `entry.path` is  `code//a/b/c/d.json`, its an abnormal tar file, but it exists. And stirp is `1`.
In 6.2.0, the final `absolute path` will be `/Users/admin/unpacked/a/b/c/d.json`, it's right;
in 6.2.1, the final `absolute path` will be `/a/b/c/d.json`, this will cause error, which  lead to `checkpath` return false;

**Comment by isaacs** [comment]
@rzyanhao Please provide a tar file and some code that shows the error, not an english description. I only can understand this sort of thing if it's expressed in code. As far as I can tell, the code is correct now, and was not correct before.
