### ISSUE TITLE
Documentation: including multiple unrelated directories without leading directory elements in a single archive

### ISSUE THREAD

**Issue by aral** [isaacs/node-tar#415]
Not sure if this is the best way to do this but given it took me a moment to figure it out (as it does not seem to be a natively-supported use case), I thought I’d document it.

Please feel free to add to the documentation/examples or to close this and folks will still be able to find it if they search for it.

TL; DR: use symlinks.

> How to include multiple directories from different places in the file system hierarchy in an archive without including the whole directory structure for any of them.
> 
> https://codeberg.org/aral/gists/src/branch/main/how-to-include-multiple-directories-from-different-places-in-the-file-system-hierarchy-in-an-archive-without-including-the-whole-directory-structure-for-any-of-them.md

**Comment by isaacs** [comment]
You could also append them to an archive.

Eg, to add `/some/path/asdf` and `/other/path/foo` to the same archive, do this:

```ts
const file = '/path/to/file.tar'
await tar.u({ file, cwd: '/some/path' }, ['asdf'])
await tar.u({ file, cwd: '/other/path' }, ['foo'])
```
