### ISSUE TITLE
Compilation error for CommonJs modules

### ISSUE THREAD

**Issue by Goodwine** [isaacs/node-tar#422]
Hello, similar to the previous type errors in tar, I found another error when trying to compile tar in commonjs modules.

Repro gist is here:
https://gist.github.com/Goodwine/4cc0f2c078c6fb163006633c0ef48fad

Repro steps:
```
npm install
npx tsc
```

Error message:
```
node_modules/minizlib/dist/commonjs/index.d.ts:6:8 - error TS1192: Module '"zlib"' has no default export.

6 import realZlib from 'zlib';
         ~~~~~~~~


Found 1 error in node_modules/minizlib/dist/commonjs/index.d.ts:6
```

**Comment by isaacs** [comment]
Yeah, that's why `tsc` isn't the command to use. Run `npm prepare`, it has to use the specific tsconfig values that tshy provides. `npx tsc` will never work here.

**Comment by nex3** [comment]
To be clear, it isn't `node-tar` itself where the compilation error is occurring, it's in @Goodwine's sample package that _uses_ `node-tar`. This sample package doesn't have an `npm prepare` script. Unless you're saying that the `node-tar` package is intentionally incompatible with out-of-the-box TSC?

**Comment by isaacs** [comment]
The issue is that `esModuleCompatibility` and `skipLibCheck` are both set to `false`.

`skipLibCheck: true` is recommended. If you are not going to skipLibCheck, then you must enable `esModuleCompatibility` for this module to type check properly.

**Comment by nex3** [comment]
So it _is_ intentional that this is incompatible with out-of-the-box TSC?

**Comment by isaacs** [comment]
"Out of the box tsc" without any configuration is incompatible with modern node, hybrid modules, ESM, and lots of other stuff, so... yeah? You have to configure tsc to use it, that's just how it is. Take it up with Microsoft.
