### ISSUE TITLE
Move / rename files on extract

### ISSUE THREAD

**Issue by hudlow** [isaacs/node-tar#423]
It appears that `onWriteEntry` lets you move or rename a file when it's going into an archive, but can you do the same with `transform` or `onReadEntry` for files coming out of an archive? `strip` seems like a special case of this, but I'm trying to work out if I can transform _and rename_ files without first writing them to disk and worrying about races.

**Comment by pdutourgeerling** [comment]
This is already possible :). For example, the following code extracts an archive while ignoring the folder structure

```
fs.createReadStream(archivePath)
    .pipe(decompressor)
    .pipe(tar.extract({
        onReadEntry: entry => {
            entry.path = path.basename(entry.path)
        }
    }))
```
